### ISSUE TITLE
Documentation & Website Generation: A Proposal

### ISSUE THREAD

**Issue by spikhoff** [mattiasclaesson/TuningSuites#61]
Hi,

http://www.txsuite.org seems to be offline.

As we continue to grow and evolve the project, the importance of comprehensive and accessible documentation becomes increasingly evident. To better serve our users and maintain project integrity, I propose the following:

- Centralized Documentation: Add documentation to existing repository to house all project documentation. This will ensure a single source of truth and facilitate easier maintenance.
- Automated Website Generation: Utilize a suitable tool or framework to automatically generate a user-friendly website from our repository's documentation. This will provide a dedicated platform for users to access and navigate information. (doxygen?)
- Consistent Formatting and Style: Enforce a consistent style guide for all documentation to enhance readability and maintainability. Consider using tools like Markdown.
- Community Involvement: Foster community contributions to documentation by encouraging users to submit corrections, additions, and suggestions. This will ensure the documentation remains accurate and relevant.

By implementing these measures, we can significantly improve the overall user experience and promote the long-term success of our project.
I invite the community to discuss this proposal and provide feedback.

**Comment by mattiasclaesson** [comment]
Hi,

Fixed it for now, its the ISP that very seldom change my IP. 

Plan is obviously to decommission the txsuite.org when possible.

Documentation should be here on github in my opinion.

I have updated the trioniccanflasher to automatically find new versions on github instead of the legacy automupdate site. Now I am only waiting for manic to upload the new version to the old location. 

A similar update could be created for the suites. All suite would have to be released as one package, but I think that is the best that can be done at this point in time.
